OnlineShop/Areas/Admin/Controllers/ProductManagementController.cs
using Models.DAO;
using Models.Entity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;

namespace OnlineShop.Areas.Admin.Controllers
{
    public class ProductManagementController : BaseController
    {
        DanhMucSanPhamDao dmDao = new DanhMucSanPhamDao();
        LoaiSPDao loaiSPDao = new LoaiSPDao();
        // GET: Admin/ProductManagement
        public ActionResult Index(int pagenumber=1,int pagesize=5)
        {
            SanPhamDao spDao = new SanPhamDao();
            return View(spDao.listProduct(pagenumber,pagesize));
        }
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.danhmucsanpham = dmDao.li();
            ViewBag.loaisanpham = loaiSPDao.dsLoaiSP();
            return View();
        }
        [HttpPost]
        public ActionResult CreateProduct(SanPham sp, HttpPostedFileBase linkanh)
        {
            ViewBag.danhmucsanpham = dmDao.li();
            ViewBag.loaisanpham = loaiSPDao.dsLoaiSP();
            try
            {
                // lấy tên của hình ảnh
                var tenfile = Path.GetFileName(linkanh.FileName);
                // tạo đường dẫn
                var duongdan = Path.Combine(Server.MapPath("/Photo"), tenfile);
                if (System.IO.File.Exists(duongdan))
                {
                    sp.linkanh = linkanh.FileName;
                    ViewBag.loi = "Hình ảnh đã tồn tại";
                }
                else
                {
                    linkanh.SaveAs(duongdan);
                    sp.linkanh = linkanh.FileName;
                }
              
            }
            catch (Exception)
            {
                ViewBag.loianh = "Chọn hình ảnh"; 
                return View("Create");

            }
            if (ModelState.IsValid)
            {
                SanPhamDao spDao = new SanPhamDao();

                spDao.Create(sp);
                return Redirect("Index");
            }

            return View("Create");
        }
        [HttpGet]
        public ActionResult Edit(int masanpham)
        {
            ViewBag.danhmucsanpham = dmDao.li();
            ViewBag.loaisanpham = loaiSPDao.dsLoaiSP();
            SanPhamDao spDao = new SanPhamDao();
            return View(spDao.searchProduct(masanpham));
        }
        [HttpPost]
        public ActionResult EditProduct(SanPham sp, HttpPostedFileBase linkanh)
        {
            ViewBag.danhmucsanpham = dmDao.li();
            ViewBag.loaisanpham = loaiSPDao.dsLoaiSP();
            try
            {
                // lấy tên của hình ảnh
                var tenfile = Path.GetFileName(linkanh.FileName);
                // tạo đường dẫn
                var duongdan = Path.Combine(Server.MapPath("/Photo"), tenfile);
                if (System.IO.File.Exists(duongdan))
                {
                    sp.linkanh = linkanh.FileName;
                    ViewBag.loi = "Hình ảnh đã tồn tại";
                }
                else
                {
                    linkanh.SaveAs(duongdan);
                    sp.linkanh = linkanh.FileName;
                }
            }
            catch (Exception)
            {
                SanPhamDao spDao = new SanPhamDao();
                sp.linkanh = spDao.searchProduct(sp.masanpham).linkanh;
            }
            if (ModelState.IsValid)
            {
                SanPhamDao spDao = new SanPhamDao();
                spDao.Edit(sp);
                return Redirect("Index");
            }
            else
            {
                return View("Edit", sp);
            }

        }

        public ActionResult Delete(int masanpham)
        {
            try
            {
                SanPhamDao spDao = new SanPhamDao();
                spDao.Delete(masanpham);
            }
            catch (Exception)
            {

               
            }
            return RedirectToAction("Index");
        }
        public ActionResult TimKiem(string timkiem)
        {
            SanPhamDao spDao = new SanPhamDao();
            return View("TimKiem",spDao.timkiem(timkiem,0));
        }
    }
}

OnlineShop/Areas/Admin/Views/ProductManagement/Create.cshtml
@model Models.Entity.SanPham

@using Models.Entity

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
}
@using (@Html.BeginForm("CreateProduct", "ProductManagement", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    <div class="row">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="col-md-6">
            <div class="box-body">
                <div class="form-group">
                    <label for="exampleInputEmail1">Tên sản phẩm</label>
                    <input type="text" class="form-control" id="tensanpham" name="tensanpham" placeholder="Tên sản phẩm" style="border-radius: 0;box-shadow:none; border-color: #d2d6de;">
                    @Html.ValidationMessageFor(model => model.tensanpham, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Giá cả</label>
                    <input type="text" class="form-control" id="giaban" name="giaban" placeholder="Giá bán" style="border-radius: 0;box-shadow:none; border-color: #d2d6de;">
                    @Html.ValidationMessageFor(model => model.giaban, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Mô tả</label>
                    <textarea  class="form-control"  id="mota" name="mota" placeholder="Mô tả sản phẩm" style="border-radius: 0;box-shadow:none; border-color: #d2d6de;"></textarea>
                    @Html.ValidationMessageFor(model=>model.mota,"",new { @class="text-danger"})
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Số lượng</label>
                    <input type="number" class="form-control" id="soluong" name="soluong" placeholder="số lượng" style="border-radius: 0;box-shadow:none; border-color: #d2d6de;">
                    @Html.ValidationMessageFor(model => model.soluong, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Xuất xứ</label>
                    <select class="form-control" style="border-radius: 0;box-shadow:none; border-color: #d2d6de;" name="xuatxu" id="xuatxu">
                        <option id="1" value="Hàn Quốc">Hàn Quốc</option>
                        <option id="2" value="Việt Nam" selected="2">Việt Nam</option>
                        <option id="3" value="Trung Quốc">Trung Quốc</option>
                        <option id="4" value="Nhật Bản">Nhật Bản</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="exampleInputFile">Chọn ảnh</label>
                    <input type="file" id="linkanh" value="Chọn ảnh" name="linkanh">
                    @Html.ValidationMessageFor(model => model.linkanh, "", new { @class = "text-danger" })
                    <span class="text-danger">@ViewBag.loianh</span>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Thêm mới</button>
            </div> 
        </div>
        <div class="col-md-6">
            <div class="box-body">
                <div class="form-group">
                    <label for="exampleInputEmail1">Danh mục sản phẩm</label>
                    <select class="form-control" style="border-radius: 0;box-shadow:none; border-color: #d2d6de;" name="madanhmuc" id="madanhmuc">
                        @foreach(var item in (List<DanhMucSanPham>)ViewBag.danhmucsanpham)
                        {
                            <option id="@item.madanhmucsanpham" value="@item.madanhmucsanpham">@item.tendanhmucsanpham</option>
                        }
                    </select>
                    
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Loại sản phẩm</label>
                    <select class="form-control" style="border-radius: 0;box-shadow:none; border-color: #d2d6de;" name="maloaisanpham" id="maloaisanpham">
                        @foreach (var item in (List<LoaiSanPham>)ViewBag.loaisanpham)
                        {
                            <option id="@item.maloaisanpham" value="@item.maloaisanpham">@item.tenloaisanpham</option>
                        }
                    </select>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Ưu tiên sản phẩm</label>
                    <select class="form-control" style="border-radius: 0;box-shadow:none; border-color: #d2d6de;" name="uutien" id="uutien">
                       <option id="1" value="1"> Sản phẩm thường</option>
                       <option id="2" value="2">Sản phẩm khuyến mãi</option>
                       <option id="3" value="3">Sản phẩm mới</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Chi tiết sản phẩm</label>
                    <textarea class="form-control" id="chitiet" name="chitiet" placeholder="Chi tiết sản phẩm" style="border-radius: 0;box-shadow:none; border-color: #d2d6de; height:150px;"></textarea>
                </div>
            </div>
        </div>
     
   </div>  
}

OnlineShop/Areas/Admin/Views/ProductManagement/Edit.cshtml
@model Models.Entity.SanPham
@using Models.Entity

@{
    ViewBag.Title = "Chỉnh xửa";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
}
@using (@Html.BeginForm("EditProduct", "ProductManagement", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken();
    <div class="row">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="col-md-6">
            <div class="box-body">
                <div class="form-group">
                    <label for="exampleInputEmail1">Mã sản phẩm</label>
                    <input type="text" readonly="readonly"class="form-control" id="masanpham" name="masanpham" style="border-radius: 0;box-shadow:none; border-color: #d2d6de;" value="@Model.masanpham">
                    @Html.ValidationMessageFor(model => model.tensanpham, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Tên sản phẩm</label>
                    <input type="text" class="form-control" id="tensanpham" name="tensanpham" placeholder="Tên sản phẩm" style="border-radius: 0;box-shadow:none; border-color: #d2d6de;" value="@Model.tensanpham">
                    @Html.ValidationMessageFor(model => model.tensanpham, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Giá cả</label>
                    <input type="text" value="@Model.giaban" class="form-control" id="giaban" name="giaban" placeholder="Giá bán" style="border-radius: 0;box-shadow:none; border-color: #d2d6de;">
                    @Html.ValidationMessageFor(model => model.giaban, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Mô tả</label>
                    <textarea class="form-control" id="mota" name="mota" placeholder="Mô tả sản phẩm" style="border-radius: 0;box-shadow:none; border-color: #d2d6de;">@Model.mota</textarea>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Số lượng</label>
                    <input type="number" value="@Model.soluong" class="form-control" id="soluong" name="soluong" placeholder="Số lượng" style="border-radius: 0;box-shadow:none; border-color: #d2d6de;">
                    @Html.ValidationMessageFor(model => model.soluong, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Xuất xứ</label>
                    <select class="form-control" style="border-radius: 0;box-shadow:none; border-color: #d2d6de;" name="xuatxu" id="xuatxu">
                        <option id="1" value="Hàn Quốc" selected>Hàn Quốc</option>
                        <option id="2" value="Việt Nam">Việt Nam</option>
                        <option id="3" value="Trung Quốc">Trung Quốc</option>
                        <option id="4" value="Nhật Bản">Nhật Bản</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="exampleInputFile">Chọn ảnh</label>
                    <input type="file" id="linkanh" value="Chọn ảnh" name="linkanh">
                    @Html.ValidationMessageFor(model => model.linkanh, "", new { @class = "text-danger" })<br />
                    <img src="@Url.Content("/Photo/"+@Model.linkanh)" style="width:100px;height:100px;"/>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
    <a href="~/Admin/ProductManagement/Index"><button class="btn btn-link">Quay về</button></a>
    <button type="submit" class="btn btn-primary">Chỉnh sửa</button>
        </div>
        </div>
        <div class="col-md-6">
            <div class="box-body">
                <div class="form-group">
                    <label for="exampleInputEmail1">Danh mục sản phẩm</label>
                    <select class="form-control" style="border-radius: 0;box-shadow:none; border-color: #d2d6de;" name="madanhmuc" id="madanhmuc">
                        @foreach (var item in (List<DanhMucSanPham>)ViewBag.danhmucsanpham)
                        {
                            var select = "";

                            if (Model.madanhmuc == @item.madanhmucsanpham)
                            {
                                select = "selected";
                            }
                            <option @select id="@item.madanhmucsanpham" value="@item.madanhmucsanpham">@item.tendanhmucsanpham</option>
                        }
                    </select>

                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Loại sản phẩm</label>
                    <select class="form-control" style="border-radius: 0;box-shadow:none; border-color: #d2d6de;" name="maloaisanpham" id="maloaisanpham">
                        @foreach (var item in (List<LoaiSanPham>)ViewBag.loaisanpham)
                        {
                            var select = "";

                            if (Model.maloaisanpham == @item.maloaisanpham)
                            {
                                select = "selected";
                            }
                            <option  @select id="@item.maloaisanpham" value="@item.maloaisanpham">@item.tenloaisanpham</option>
                        }
                    </select>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Ưu tiên sản phẩm</label>
                    <select class="form-control" style="border-radius: 0;box-shadow:none; border-color: #d2d6de;" name="madanhmuc" id="madanhmuc">
                        <option id="1" selected="@Model.uutien" value="1"> Sản phẩm thường</option>
                        <option id="2" value="2">Sản phẩm khuyến mãi</option>
                        <option id="3" value="3">Sản phẩm mới</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Chi tiết sản phẩm</label>
                    <textarea class="form-control" id="chitiet" name="chitiet" placeholder="Chi tiết sản phẩm" style="border-radius: 0;box-shadow:none; border-color: #d2d6de; height:150px;"></textarea>
                </div>
            </div>
        </div>

    </div>
}

OnlineShop/Areas/Admin/Views/ProductManagement/Index.cshtml
@using Models.Entity;
@using PagedList.Mvc;
@model PagedList.IPagedList<SanPham>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
}

<div class="box-body">
    <div class="panel-heading">
        @Html.ActionLink("Thêm mới sản phẩm", "Create", "ProductManagement")
    </div>
    <table id="example2" class="table table-bordered table-hover">
        <caption style="text-align:center"><i><b>DANH SÁCH SẢN PHẨM</b></i></caption>
        <thead>
            <tr>
                <th>Mã SP</th>
                <th>Tên sản phẩm</th>
                <th>Giá bán</th>
                <th>Số lượng</th>
                <th>Ảnh</th>
                <th>Chức năng</th>
            </tr>
        </thead>
        <tbody>
           @foreach (var item in Model)
           {
            <tr>
                <td>@item.masanpham</td>
                <td>
                  @item.tensanpham
                </td>
                <td>@item.giaban VND</td>
                <td>@item.soluong</td>
                <td> <img src="@Url.Content("/Photo/"+@item.linkanh)" style="width:70px;height:70px;" alt="Chưa có ảnh"/></td>
                <td style="text-align:center;"><a href="/Admin/ProductManagement/Edit?masanpham=@item.masanpham"><span class="glyphicon glyphicon-edit"></span></a>--<a href="/Admin/ProductManagement/Delete?masanpham=@item.masanpham" onclick="return confirm('Bạn có muốn xóa ?')"><span class="glyphicon glyphicon-trash"></span></a></td>
            </tr>
           }

            
        </tbody>
        <tfoot>
            <tr>
            
            </tr>
        </tfoot>
    </table>
    @Html.PagedListPager(Model, pagenumber=>Url.Action("Index",new { pagenumber}))
</div>

OnlineShop/Areas/Admin/Views/ProductManagement/TimKiem.cshtml
@using Models.Entity;
@using PagedList.Mvc;
@model List<Models.Entity.SanPham>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
}

<div class="box-body">
    <div class="panel-heading">
    </div>
    <table id="example2" class="table table-bordered table-hover">
        <caption style="text-align:center"><i><b>Kết quả tìm kiếm</b></i></caption>
        <thead>
            <tr>
                <th>Mã SP</th>
                <th>Tên sản phẩm</th>
                <th>Giá bán</th>
                <th>Số lượng</th>
                <th>Ảnh</th>
                <th>Chức năng</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.masanpham</td>
                    <td>
                        @item.tensanpham
                    </td>
                    <td>@item.giaban VND</td>
                    <td>@item.soluong</td>
                    <td> <img src="@Url.Content("/Photo/"+@item.linkanh)" style="width:70px;height:70px;" alt="Chưa có ảnh" /></td>
                    <td style="text-align:center;"><a href="/Admin/ProductManagement/Edit?masanpham=@item.masanpham"><span class="glyphicon glyphicon-edit"></span></a>--<a href="/Admin/ProductManagement/Delete?masanpham=@item.masanpham" onclick="return confirm('Bạn có muốn xóa ?')"><span class="glyphicon glyphicon-trash"></span></a></td>
                </tr>
            }


        </tbody>
        <tfoot>
            <tr></tr>
        </tfoot>
    </table>
</div>