OnlineShop/Models/ShopingCart.cs
using Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineShop.Models
{
    public class ShopingCart
    {
        public ShopingCart() { }

        public List<ItemCart> listItem = new List<ItemCart>();
        public void AddItem(SanPham sp, int soluong=1)
        {

            if (listItem.Exists(item => item.sanpham.masanpham == sp.masanpham))
            {
                listItem.Find(i => i.sanpham.masanpham == sp.masanpham).soluong += soluong;
            }
            else
            {
                listItem.Add(new ItemCart() { sanpham = sp, soluong = soluong });
            }
        }
        public void UpdateAmount(SanPham sp, int soluong)
        {
            listItem.Find(i => i.sanpham.masanpham == sp.masanpham).soluong = soluong;
        }
        public void ReMove(SanPham sp)
        {
            listItem.Remove(listItem.Find(i => i.sanpham.masanpham == sp.masanpham));
        }
        public decimal TotalMoney()
        {
            decimal? tongtien = 0;
            foreach (ItemCart item in listItem)
            {
                tongtien += item.soluong * item.sanpham.giaban;
            }
            return tongtien.Value;
        }
        public int TotalAmmount()
        {
            int soluong = 0;
            foreach (ItemCart item in listItem)
            {
                soluong += item.soluong;
            }
            return soluong;
        }
    }
}

OnlineShop/Controllers/ShopingCartController.cs
using Models.DAO;
using Models.Entity;
using OnlineShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Controllers
{
    public class ShopingCartController : Controller
    {
        // GET: ShopingCart
        public const string shop = "Shopping";
        public ActionResult Index()
        {
            ShopingCart cart = (ShopingCart)Session[shop];
            if (cart != null)
            {
                List<ItemCart> li = new List<ItemCart>();
                li = cart.listItem;
                ViewBag.tongtien = cart.TotalMoney();
                ViewBag.soluong = cart.TotalAmmount();
                return View("Index", li);
            }
            return View("Error");
        }
        public ActionResult AddItem(int id, int soluong = 1)
        {
            SanPhamDao spDao = new SanPhamDao();
            SanPham sp = spDao.searchProduct(id);
            ShopingCart cart = (ShopingCart)Session[shop];
            if (cart == null)
            {
                cart = new ShopingCart();
            }
            cart.AddItem(sp, soluong);
            Session[shop] = cart;
            return Redirect(Request.UrlReferrer.ToString());
        }
        public ActionResult Delete(int id)
        {
            SanPhamDao spDAo = new SanPhamDao();
            SanPham sp = spDAo.searchProduct(id);
            ShopingCart cart = (ShopingCart)Session[shop];
            cart.ReMove(sp);
            Session[shop] = cart;
            return Redirect(Request.UrlReferrer.ToString());
        }
        [HttpPost]
        public ActionResult Update(int masanpham, int soluong)
        {
            SanPhamDao spDao = new SanPhamDao();
            SanPham sp = spDao.searchProduct(masanpham);
            ShopingCart cart = (ShopingCart)Session[shop];
            cart.UpdateAmount(sp, soluong);
            Session[shop] = cart;
            return Redirect(Request.UrlReferrer.ToString());
        }
        public ActionResult ThanhToan()
        {
            ShopingCart cart = (ShopingCart)Session[shop];
            if (cart != null)
            {
                List<ItemCart> li = new List<ItemCart>();
                li = cart.listItem;
                ViewBag.tongtien = cart.TotalMoney();
                ViewBag.soluong = cart.TotalAmmount();
                return View("ThanhToan", li);
            }
            else
            {
                return View("Error");
            }
        }
        [HttpPost]
        public ActionResult ThanhToan1(Models.KhachHangDTO kh)
        {
            ShopingCart cart = (ShopingCart)Session[shop];
            List<ItemCart> li = new List<ItemCart>();
            li = cart.listItem;
            ViewBag.tongtien = cart.TotalMoney();
            ViewBag.soluong = cart.TotalAmmount();
            if (ModelState.IsValid)
            {
                KhachHang kh1 = new KhachHang();
                kh1.tenkhachhang = kh.tenkhachhang;
                kh1.diachi = kh.diachi;
                kh1.email = kh.email;
                kh1.sodienthoai = kh.sodienthoai;
                KhachHangDao khDAo = new KhachHangDao();
                int makhachhang1= khDAo.ThemKhachHang(kh1);

                GioHang gh = new GioHang();
                gh.makhachhang = makhachhang1;
                gh.ngaydathang = DateTime.Today;
                gh.tinhtranggiaohang = false;
                gh.tongtien= cart.TotalMoney();
                GioHangDAO ghDao = new GioHangDAO();
                int magiohang=ghDao.ThemGioHang(gh);

                foreach (ItemCart item in li)
                {
                    ChiTietGioHang ct = new ChiTietGioHang()
                    {
                        magiohang = magiohang,
                        masanpham = item.sanpham.masanpham,
                        soluong = item.soluong,
                        thanhtien = item.soluong*(item.sanpham.giaban)
                    };
                    ChiTietGioHangDAO ctDao = new ChiTietGioHangDAO();
                    ctDao.ThemChiTiet(ct);
                }
                Session[shop] = null;
                return View("Success");
            }
            else
            {

                return View("ThanhToan", li);
            }
        }
    }
}

OnlineShop/Views/ShopingCart/Index.cshtml
@model IEnumerable<OnlineShop.Models.ItemCart>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MyLayout2.cshtml";
}
<div class="container">
    <table id="example2" class="table table-bordered table-hover">
        <caption style="text-align:center"><i><b>Danh Sách Sản Phẩm Đã Mua</b></i></caption>
        <thead>
            <tr>
                <th>Mã sản phẩm</th>
                <th>Tên sản phẩm</th>
                <th>Ảnh</th>
                <th>Số lượng</th>
                <th>Giá thành</th>
                <th>Thành tiên</th>
                <th>Chức năng</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.sanpham.masanpham</td>
                    <td>
                        @item.sanpham.tensanpham
                    </td>
                    <td> <img src="@Url.Content("/Photo/"+@item.sanpham.linkanh)" style="width:70px;height:70px;" alt="Chưa có ảnh" /></td>
                    <td align="center">
                        @using (Html.BeginForm("Update", "ShopingCart", FormMethod.Post))
                        {
                            <input type="hidden" value="@item.sanpham.masanpham" name="masanpham"/>
                            <input type="number" max="100" min="1" value="@item.soluong" name="soluong" id="soluong" onchange="return loi()" /><input  type="submit" value="OK" />
                        }
                   
                    </td>
                    <td>@item.sanpham.giaban</td>
                    <td>@item.thanhtien().ToString()</td>
                    <td><a href="/ShopingCart/Delete/@item.sanpham.masanpham">Xóa</a></td>
                </tr>
             
            }
        </tbody>
    </table>
    <div>
        <div class="col-lg-4">
            <span class="text-info">
                Tổng tiền:@ViewBag.tongtien<br />
                Số lượng : @ViewBag.soluong
            </span>
        </div>
     <div class="col-lg-8 text-right">
         <a href="/Home/Index"><img src="@Url.Content("/Photo/cart_btn_2.png")"alt="no"/></a>
         <a href="/ShopingCart/ThanhToan"><img src="@Url.Content("/Photo/cart_btn_3.png")" alt="no" /></a>
     </div>
       
    </div>
</div>
<script type="text/javascript">
    function loi() {
        if (document.getElementById("soluong").value.length<=0) {
            document.getElementById("soluong").value = 1;
            alert("Số lượng không hợp lệ ! Vui lòng nhập số lượng");
        }
        if (document.getElementById("soluong").value < 0 || document.getElementById("soluong").value > 100) {
            document.getElementById("soluong").value = 1;
            alert("Số lượng không hợp lệ ! Bạn chỉ đươc mua từ 1->100 sản phẩm");
        }
    }

</script>

OnlineShop/Views/ShopingCart/Success.cshtml
@{
    ViewBag.Title = "Success";
    Layout = "~/Views/Shared/_MyLayout2.cshtml";
}
<div class="container">
    <h2 class="text-info text-center">Bạn đã mua hàng thành công ! </h2>
</div>

OnlineShop/Views/ShopingCart/ThanhToan.cshtml
@model IEnumerable<OnlineShop.Models.ItemCart>
@{
    ViewBag.Title = "ThanhToan";
    Layout = "~/Views/Shared/_MyLayout2.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-5">
            @using (Html.BeginForm("ThanhToan1", "ShopingCart", FormMethod.Post))
        {
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="box-body">
                    <div class="form-group">
                        <label for="exampleInputPassword1">Tên khách hàng</label>
                        <input type="text" class="form-control" id="tenkhachhang" name="tenkhachhang" placeholder="Tên khách hàng" style="border-radius: 0;box-shadow:none; border-color: #d2d6de;">
                        @Html.ValidationMessage("tenkhachhang","",new { @class="text-danger"})
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Số điện thoại</label>
                        <input type="text" class="form-control" id="sodienthoai" name="sodienthoai" placeholder="Số điện thoại" style="border-radius: 0;box-shadow:none; border-color: #d2d6de;">
                        @Html.ValidationMessage("sodienthoai", "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Email</label>
                        <input type="text" class="form-control" id="email" name="email" placeholder="Email" style="border-radius: 0;box-shadow:none; border-color: #d2d6de;">
                        @Html.ValidationMessage("email", "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Địa chỉ giao hàng</label>
                        <input type="text" class="form-control" id="diachi" name="diachi" placeholder="Địa chỉ giao hàng" style="border-radius: 0;box-shadow:none; border-color: #d2d6de;">
                        @Html.ValidationMessage("diachi", "", new { @class = "text-danger" })
                    </div>
                </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Đặt hàng</button>
                    </div>
        }
        </div>
        <div class="col-md-7">
            <table id="example2" class="table table-bordered table-hover">
                <caption style="text-align:center"><i><b>Danh Sách Sản Phẩm Đã Mua</b></i></caption>
                <thead>
                    <tr>
                        <th>Tên sản phẩm</th>
                        <th>Số lượng</th>
                        <th>Giá thành</th>
                        <th>Thành tiên</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                {
                        <tr>
                            <td>
                                @item.sanpham.tensanpham
                            </td>
                            <td align="center">
                                <input type="text" readonly value="@item.soluong" />
                            </td>
                            <td>@item.sanpham.giaban</td>
                            <td>@item.thanhtien().ToString()</td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
</div>